homeassistant:
  # Name of the location where Home Assistant is running
  name: Thuis
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 11
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize_glob: !include customize_glob.yaml
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# hacs:
#   token: !secret hacs_github_token

# Discover some devices automatically
#discovery:

# Devices
sensor: !include devices/sensor.yaml

binary_sensor: !include devices/binary_sensor.yaml

switch: !include devices/switch.yaml

light: !include devices/light.yaml

notify: !include devices/notify.yaml

alert: !include devices/alert.yaml

input_boolean: !include devices/input_boolean.yaml

rflink:
  host: !secret rflink_host
  port: !secret rflink_port
# RFLink version+config: (output seen via USB in RFLinkLoader v1.11)
# 20;01;VER=1.1;REV=48;BUILD=04;
# 10;status;
# 20;02;STATUS;setRF433=ON;setNodoNRF=OFF;setMilight=OFF;setLivingColors=OFF;setAnsluta=OFF;setGPIO=OFF;setBLE=OFF;setMysensors=OFF;

# Pi-Hole is deprecated for HA, look into AdGuard instead?  https://community.home-assistant.io/t/home-assistant-community-add-on-pi-hole/33817
# pi_hole:
#   - host: !secret pihole_host
#     api_key: !secret pihole_apikey
#     name: pi_hole
#     ssl: false
#     verify_ssl: false

# Text to speech
#tts:
#  - platform: google_translate

#media_player:
#  - platform: plex
#  - platform: spotify
#    client_id: !secret spotify_client_id
#    client_secret: !secret spotify_client_secret
#    aliases:
#      4a4eece177e2ddd2996edc30482fa2d6: 'TV'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

#panel_iframe:
#  grafana:
#    title: Grafana
#    icon: mdi:chart-timeline
#    url: !secret panel_iframe_grafana_url

recorder:
  purge_keep_days: 30

logger:
  default: error
  logs:
    rflink: debug
    homeassistant.components.rflink: debug
