- platform: yr
- platform: postnl
  username: !secret postnl_username
  password: !secret postnl_password
- platform: plex
  host: !secret plex_host
  port: !secret plex_port
  name: Plex
  token: !secret plex_token
  ssl: true
  verify_ssl: false
- platform: dsmr
  host: !secret dsmr_host
  port: !secret dsmr_port
  dsmr_version: 4
- platform: rflink
  automatic_add: false
  devices:
    cresta_2d01_bat:
      #name: Cresta_woonkamer_bat
      sensor_type: battery
    cresta_2d01_hum:
      #name: Cresta_woonkamer_hum
      sensor_type: humidity
    cresta_2d01_temp:
      #name: Cresta_woonkamer_temp
      sensor_type: temperature
    cresta_6603_bat:
      #name: Cresta_keuken_bat
      sensor_type: battery
    cresta_6603_hum:
      #name: Cresta_keuken_hum
      sensor_type: humidity
    cresta_6603_temp:
      #name: Cresta_keuken_temp
      sensor_type: temperature
    cresta_2a01_bat:
      #name: Cresta_buiten_bat
      sensor_type: battery
    cresta_2a01_hum:
      #name: Cresta_buiten_hum
      sensor_type: humidity
    cresta_2a01_temp:
      #name: Cresta_buiten_temp
      sensor_type: temperature
- platform: pi_hole
  host: !secret pihole_host
- platform: buienradar
  timeframe: 5
  monitored_conditions:
    - symbol
    - humidity
    - temperature
    - windspeed
    - pressure
    - rainchance_1d
    - rain_1d