esphome:
  name: woonkamer_kast_light
  # FKA esp8266_h801_led_rgb
  platform: ESP8266
  board: esp01_1m

# H801 led rgbww connected to IKEA Dioder strips
# First flash: connect 3.3V FTDI flash, might have to connect a pin (0?) to GND or hold a button.

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: wifi_signal
    name: "Woonkamer Kast Light WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Woonkamer Kast Light Uptime"
    
#RGBWarm
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
#  - platform: esp8266_pwm
#    pin: 14
#    frequency: 1000 Hz
#    id: pwm_w1
#  - platform: esp8266_pwm
#    pin: 4
#    frequency: 1000 Hz
#    id: pwm_w2
    
light:
  - platform: rgb
    name: "Woonkamer Kast Light RGB"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    #white: pwm_w1
    effects:
      - random:
      - flicker:
      - strobe:
  
text_sensor:
  - platform: version
    name: "Woonkamer Kast Light Firmware version"