substitutions:
  name: "kantoor-plug"
  relay_restore_mode: ALWAYS_ON
packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: 3aM8Xi0qI5agHlQxZSTYbnzB3KD31CGD2wnLZszyNLM=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  use_address: 192.168.2.152
