esphome:
  name: mini_display_test
  platform: ESP32
  board: ttgo-lora32-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "broodje_WESP"
    password: !secret fallback_ap_password

captive_portal:


# Enable logging 
logger:

# Enable Home Assistant API
api:

ota:

# Get the time from Home Assistant to sync the onboard real-time clock.
time:
  - platform: homeassistant
    id: esptime

sensor:
  - platform: wifi_signal
    name: "WESP WiFi Signal Sensor"
    update_interval: 60s
  # Get temperature sensors imported from Home Assistant.
  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.keuken_hue_motion_sensor_temperature
    internal: true
    
i2c:
  sda: 5
  scl: 4
  
font:
  - file: 'slkscr.ttf'
    id: font1
    size: 8

  - file: 'BebasNeue-Regular.ttf'
    id: font2
    size: 48

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    #reset_pin: D0
    address: 0x3C
    id: my_display
    pages:
      - id: page1
        lambda: |-
          // Print "Hallo Wereld" in top center.
          it.printf(64, 0, id(font1), TextAlign::TOP_CENTER, "Hallo Wereld");
          
          // Print time in HH:MM format
          it.strftime(0, 60, id(font2), TextAlign::BASELINE_LEFT, "%H:%M", id(esptime).now());
          
          // Print inside temperature (from homeassistant sensor)
          if (id(inside_temperature).has_state()) {
            it.printf(127, 23, id(font1), TextAlign::TOP_RIGHT , "%.1f°", id(inside_temperature).state);
          }
      - id: page2
        lambda: |-
          // Print inside temperature (from homeassistant sensor)
          if (id(inside_temperature).has_state()) {
            it.printf(64, 0, id(font2), TextAlign::TOP_CENTER , "%.1f°", id(inside_temperature).state);
          }

# Cycle through pages on a timer 
interval: 
  - interval: 5s 
    then: 
      - display.page.show_next: my_display 
      - component.update: my_display