esphome:
  name: server-plug

esp8266:
  board: esp01_1m

# Koogeek smart plug KLSP1
# First flash: over wifi using tuya-convert tool see https://lovetechstuff.com/iot-products/how-to-flash-wifi-socket-without-disassembly/
# tuya-convert on Ubuntu 18.04 use needs patch https://github.com/ct-Open-Source/tuya-convert/issues/157#issuecomment-529238904

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "c908a4fbffb10e9a45401ef93f5d8319"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "broodje_Server-Plug"
    password: "C7FA5XYLRQJb"

captive_portal:

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO3
      inverted: True
    on_press:
      - switch.toggle: fakebutton

switch:
  - platform: template
    name: "ServerPlug Switch"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
    - light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO14
    restore_mode: RESTORE_DEFAULT_ON

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO1
      inverted: True

light:
  - platform: monochromatic
    output: pow_blue_led
    id: led

sensor:
  - platform: wifi_signal
    name: "ServerPlug WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "ServerPlug Uptime"
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: "0.0028"
    voltage_divider: "960"
    current:
      name: "ServerPlug Current"
      unit_of_measurement: A
    voltage:
      name: "ServerPlug Voltage"
      unit_of_measurement: V
    power:
      name: "ServerPlug Power"
      unit_of_measurement: W
      id: power
    change_mode_every: 8
    update_interval: 10s
  - platform: total_daily_energy
    name: "ServerPlug Total Daily Energy"
    power_id: power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy

text_sensor:
  - platform: version
    name: "ServerPlug Firmware version"

status_led:
  pin: GPIO13

time:
  - platform: sntp
    id: my_time