esphome:
  name: test_esp01_knop
  platform: ESP8266
  board: esp01_1m

# ESP01 esp8266
# First flash: 3.3v ftdi

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "broodje_test_esp01_knop"
    password: !secret fallback_ap_password

captive_portal:


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: wifi_signal
    name: "TestEsp01Knop WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "TestEsp01Knop Uptime"