esphome:
  name: tuin-veranda

esp8266:
  board: esp01_1m

# Sonoff S55
#
# Pin    Function
# GPIO0  Button (inverted)
# GPIO12 Relay and Red LED
# GPIO13 Blue LED (inverted)
# GPIO1  UART TX pin (for external sensors)
# GPIO3  UART RX pin (for external sensors)

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password_serverplug

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "broodje_Tuin-Veranda"
    password: !secret fallback_ap_password

captive_portal:

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      inverted: True
    on_press:
      - switch.toggle: fakebutton

switch:
  - platform: template
    name: "Tuin-Veranda Switch"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
    - light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    output: pow_blue_led
    id: led

sensor:
  - platform: wifi_signal
    name: "Tuin-Veranda WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Tuin-Veranda Uptime"

text_sensor:
  - platform: version
    name: "Tuin-Veranda Firmware version"